### ISSUE TITLE
Explain how to setup and run converter

### ISSUE THREAD

**Issue by Jeeppler** [gautambaghel/coverity-scan-results-to-sarif#1]
The `README.md` does not contain information on what is needed to setup and how to run the converter. Please add some information on how to get started with the converter.

**Comment by gautambaghel** [comment]
@Jeeppler hopefully readme helps now, open it again if any suggestions

**Comment by Jeeppler** [comment]
@gautambaghel thanks for adding more information to the `README.md`. However, I would like to run your converter standalone as CLI tool instead of integrating it into a GitHub Action workflow. Basically, I would like to know what I have to install (I assume NPM and a JavaScript/Nodejs runtime) as well as what dependencies are necessary and how to install them.

It would be nice have the install instructions for a Debian/Ubuntu based system.

**Comment by Jeeppler** [comment]
@gautambaghel I am unable to re-open the issue. I think you are the only one with the necessary rights to re-open the issue.

**Comment by gautambaghel** [comment]
I'm not sure if this will be helpful at this point but you can run any actions locally by following this page -> https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions

For this particular action you can run it locally by


`env INPUT_PIPELINE-RESULTS-JSON="coverity-results.json" INPUT_OUTPUT-RESULTS-SARIF="coverity-results-sarif.json" node index.js`


where coverity-results.json -> results you get from coverity

coverity-results-sarif.json -> name of the o/p sarif file
